export const inputs = [
  {
    id: "usernameInput",
    type: "text",
    placeholder: "Enter your username",
    errorMessage:
      "Username should be 3-16 characters and shouldn't include any special character!",
    pattern: "^[A-Za-z0-9]{3,16}$",
    className: "form-control",
    required: true,
  },
  {
    id: "emailInput",
    type: "email",
    placeholder: "Enter your email",
    errorMessage: "It should be a valid email address!",
    className: "form-control",
    required: true,
  },
  {
    id: "passwordInput",
    type: "password",
    placeholder: "Enter your password",
    errorMessage:
      "Password should be 8-20 characters and include at least 1 letter, 1 number and 1 special character!",
    pattern: `^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{8,20}$`,
    className: "form-control",
    required: true,
  },
  {
    id: "femaleInput",
    name: "genderInput",
    type: "radio",
    value: "1",
    defaultChecked: true,
  },
  {
    id: "maleInput",
    name: "genderInput",
    type: "radio",
    value: "2",
  },
  {
    id: "optionGenderInput",
    name: "genderInput",
    type: "radio",
    value: "3",
  },
  {
    id: "firstnameInput",
    type: "text",
    placeholder: "First name",
    errorMessage: "It should be a valid first name!",
    className: "form-control",
    required: true,
  },
  {
    id: "lastnameInput",
    type: "text",
    placeholder: "Last name",
    errorMessage: "It should be a valid first name!",
    className: "form-control",
    required: true,
  },
  {
    id: "dobInput",
    type: "date",
    required: true,
  },
  {
    id: "phoneInput",
    type: "phone",
    placeholder: "Enter your phone number",
    errorMessage: "It should be a valid phone number!",
    className: "form-control",
    required: true,
  },
  {
    id: "addressInput",
    type: "text",
    placeholder: "Enter your address",
    className: "form-control",
    required: true,
  },
  {
    id: "flexCheckDefault",
    type: "checkbox",
    className: "",
    errorMessage: "It should be a valid email address!",
    required:true,
  },
];
